const RVTeamOffensiveSnaps2023 = [
  {
    '"Team"': '"DET"',
    '"GMs"': "17",
    '"TotPlays"': "1173",
    '"Sec/Snap"': "26.5",
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"56%"',
    '"Rush%"': '"44%"',
    '"Plays"': "68",
    '"Pass"': "39",
    '"Rush"': "30",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"KC"',
    '"GMs"': "17",
    '"TotPlays"': "1131",
    '"Sec/Snap"': "26.7",
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"62%"',
    '"Rush%"': '"38%"',
    '"Plays"': "67",
    '"Pass"': "41",
    '"Rush"': "25",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"ATL"',
    '"GMs"': "17",
    '"TotPlays"': "1123",
    '"Sec/Snap"': "25.5",
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"53%"',
    '"Rush%"': '"47%"',
    '"Plays"': "66",
    '"Pass"': "35",
    '"Rush"': "31",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"CAR"',
    '"GMs"': "17",
    '"TotPlays"': "1145",
    '"Sec/Snap"': "26.4",
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Plays"': "67",
    '"Pass"': "40",
    '"Rush"': "27",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"BAL"',
    '"GMs"': "17",
    '"TotPlays"': "1122",
    '"Sec/Snap"': "27.4",
    '"No-Huddle"': '"14%"',
    '"Pass%"': '"51%"',
    '"Rush%"': '"49%"',
    '"Plays"': "65",
    '"Pass"': "33",
    '"Rush"': "32",
    '"No Play (Penalty)"': "56",
  },
  {
    '"Team"': '"HOU"',
    '"GMs"': "17",
    '"TotPlays"': "1129",
    '"Sec/Snap"': "25.8",
    '"No-Huddle"': '"14%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Plays"': "66",
    '"Pass"': "39",
    '"Rush"': "26",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"CIN"',
    '"GMs"': "17",
    '"TotPlays"': "1086",
    '"Sec/Snap"': "28",
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"64%"',
    '"Rush%"': '"36%"',
    '"Plays"': "63",
    '"Pass"': "40",
    '"Rush"': "22",
    '"No Play (Penalty)"': "56",
  },
  {
    '"Team"': '"CLE"',
    '"GMs"': "17",
    '"TotPlays"': "1231",
    '"Sec/Snap"': "25.7",
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "72",
    '"Pass"': "41",
    '"Rush"': "31",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"IND"',
    '"GMs"': "17",
    '"TotPlays"': "1143",
    '"Sec/Snap"': "25.5",
    '"No-Huddle"': '"17%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "65",
    '"Pass"': "37",
    '"Rush"': "28",
    '"No Play (Penalty)"': "55",
  },
  {
    '"Team"': '"JAC"',
    '"GMs"': "17",
    '"TotPlays"': "1160",
    '"Sec/Snap"': "26.2",
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Plays"': "68",
    '"Pass"': "41",
    '"Rush"': "27",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"MIN"',
    '"GMs"': "17",
    '"TotPlays"': "1122",
    '"Sec/Snap"': "25.6",
    '"No-Huddle"': '"16%"',
    '"Pass%"': '"64%"',
    '"Rush%"': '"36%"',
    '"Plays"': "65",
    '"Pass"': "42",
    '"Rush"': "23",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"TB"',
    '"GMs"': "17",
    '"TotPlays"': "1097",
    '"Sec/Snap"': "26.3",
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Plays"': "65",
    '"Pass"': "38",
    '"Rush"': "26",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"TEN"',
    '"GMs"': "17",
    '"TotPlays"': "1051",
    '"Sec/Snap"': "27.5",
    '"No-Huddle"': '"12%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "60",
    '"Pass"': "34",
    '"Rush"': "26",
    '"No Play (Penalty)"': "55",
  },
  {
    '"Team"': '"NO"',
    '"GMs"': "17",
    '"TotPlays"': "1154",
    '"Sec/Snap"': "26.6",
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "68",
    '"Pass"': "39",
    '"Rush"': "29",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"PIT"',
    '"GMs"': "17",
    '"TotPlays"': "1066",
    '"Sec/Snap"': "27.3",
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Plays"': "63",
    '"Pass"': "34",
    '"Rush"': "29",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"SF"',
    '"GMs"': "17",
    '"TotPlays"': "1067",
    '"Sec/Snap"': "28.9",
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Plays"': "63",
    '"Pass"': "33",
    '"Rush"': "30",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"WAS"',
    '"GMs"': "17",
    '"TotPlays"': "1104",
    '"Sec/Snap"': "26.4",
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"67%"',
    '"Rush%"': '"33%"',
    '"Plays"': "64",
    '"Pass"': "43",
    '"Rush"': "21",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"ARI"',
    '"GMs"': "17",
    '"TotPlays"': "1119",
    '"Sec/Snap"': "25.7",
    '"No-Huddle"': '"14%"',
    '"Pass%"': '"56%"',
    '"Rush%"': '"44%"',
    '"Plays"': "66",
    '"Pass"': "37",
    '"Rush"': "29",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"CHI"',
    '"GMs"': "17",
    '"TotPlays"': "1129",
    '"Sec/Snap"': "27.8",
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Plays"': "66",
    '"Pass"': "34",
    '"Rush"': "32",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"GB"',
    '"GMs"': "17",
    '"TotPlays"': "1091",
    '"Sec/Snap"': "26.7",
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"58%"',
    '"Rush%"': '"42%"',
    '"Plays"': "64",
    '"Pass"': "37",
    '"Rush"': "27",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"LV"',
    '"GMs"': "17",
    '"TotPlays"': "1041",
    '"Sec/Snap"': "26.9",
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Plays"': "61",
    '"Pass"': "36",
    '"Rush"': "25",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"DEN"',
    '"GMs"': "17",
    '"TotPlays"': "1065",
    '"Sec/Snap"': "27.2",
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"56%"',
    '"Rush%"': '"44%"',
    '"Plays"': "63",
    '"Pass"': "35",
    '"Rush"': "28",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"MIA"',
    '"GMs"': "17",
    '"TotPlays"': "1096",
    '"Sec/Snap"': "27.2",
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "64",
    '"Pass"': "37",
    '"Rush"': "28",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"LAC"',
    '"GMs"': "17",
    '"TotPlays"': "1154",
    '"Sec/Snap"': "24.7",
    '"No-Huddle"': '"14%"',
    '"Pass%"': '"62%"',
    '"Rush%"': '"38%"',
    '"Plays"': "67",
    '"Pass"': "42",
    '"Rush"': "26",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"PHI"',
    '"GMs"': "17",
    '"TotPlays"': "1146",
    '"Sec/Snap"': "27",
    '"No-Huddle"': '"17%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Plays"': "66",
    '"Pass"': "36",
    '"Rush"': "30",
    '"No Play (Penalty)"': "56",
  },
  {
    '"Team"': '"NE"',
    '"GMs"': "17",
    '"TotPlays"': "1046",
    '"Sec/Snap"': "26.1",
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Plays"': "62",
    '"Pass"': "37",
    '"Rush"': "25",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"SEA"',
    '"GMs"': "17",
    '"TotPlays"': "1042",
    '"Sec/Snap"': "25.4",
    '"No-Huddle"': '"14%"',
    '"Pass%"': '"63%"',
    '"Rush%"': '"37%"',
    '"Plays"': "61",
    '"Pass"': "38",
    '"Rush"': "23",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"LAR"',
    '"GMs"': "17",
    '"TotPlays"': "1141",
    '"Sec/Snap"': "26.8",
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "66",
    '"Pass"': "38",
    '"Rush"': "28",
    '"No Play (Penalty)"': "56",
  },
  {
    '"Team"': '"NYG"',
    '"GMs"': "17",
    '"TotPlays"': "1100",
    '"Sec/Snap"': "26.2",
    '"No-Huddle"': '"15%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Plays"': "64",
    '"Pass"': "36",
    '"Rush"': "28",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"DAL"',
    '"GMs"': "17",
    '"TotPlays"': "1180",
    '"Sec/Snap"': "26.7",
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Plays"': "69",
    '"Pass"': "41",
    '"Rush"': "29",
    '"No Play (Penalty)"': "57",
  },
  {
    '"Team"': '"BUF"',
    '"GMs"': "17",
    '"TotPlays"': "1159",
    '"Sec/Snap"': "27.5",
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Plays"': "67",
    '"Pass"': "37",
    '"Rush"': "30",
    '"No Play (Penalty)"': "56",
  },
  {
    '"Team"': '"NYJ"',
    '"GMs"': "17",
    '"TotPlays"': "1098",
    '"Sec/Snap"': "25.7",
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"64%"',
    '"Rush%"': '"36%"',
    '"Plays"': "63",
    '"Pass"': "40",
    '"Rush"': "23",
    '"No Play (Penalty)"': "56",
  },
];

export default RVTeamOffensiveSnaps2023;
